### ISSUE TITLE
Fix statement_id mapping

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#11]
Currently statement id generated with metadata included, which is not always needed.

Need to rewrite Beast to allow passing params from mapping to dumper (currently it passes only `output_uri` as string) and add flag to `statement_id` generator to specify, do we need to add metadata or not.

**Comment by Legless** [comment]
(I'll handle this, created the issue just to let you know)

**Comment by dchaplinsky** [comment]
What that change give you?
Same dozens of the statements, which are duplicates (but now with the same statement_id).

My idea is that you should decide what to do with such records on the later stage. Maybe you'd like to account for them (like show the time period when the property value was the same, or the latest date when you know that property value).

But you are raising an interesting concern. Should we indeed include ALL the meta values to the statement id hash if we going to add more meta fields like you've asked in #6. Those are definitely important but definitely needs to be ignored in the `statement_id`.
So probably instead we have to give a user an opportunity to include subset of the meta fields for the statement_key generation and provide a sane default for that?

**Comment by Legless** [comment]
> Same dozens of the statements, which are duplicates (but now with the same statement_id).

This will allow me (and my code) to easyly see these duplicates.
Currently I'm inserting data via [INSERT ... ON DUPLICATE KEY UPDATE](https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html), and having a primary/unique key on `statement_id` I'll save them into one record.

Or I could add `ON DUPLICATE KEY UPDATE meta_date = GREATEST( meta_date, 'new_value_from_statement' )`, thus saving only latest date. Or both latest and earliest. 

And you can turn this off - saving all statements with meta - if you need this. 

Currently the only option for me to do this - is to ignore generated `statement_id` and generate it by myself.

> instead we have to give a user an opportunity to include subset of the meta fields for the statement_key

This would be even better - we could ignore date but have duplicates for, for example, transformed/augmented statements. Or same statements from different sources (files/lines).

**Comment by Legless** [comment]
We can do this via optional `meta` mapping param like:

```yaml
meta:
  date:
    column: data.createdAt
    include_in_statement_id_generation: False # defaults to True, so all meta will be used
```

Or via statement dumper config:
```yaml
dump:
  cls: thebeast.dump.StatementsCSVWriter
  params:
    output_uri: "-"
    statement_id_include_meta: # empty by default, meaning use everything
#      - date
      - source
```
