### ISSUE TITLE
Resolver to generate abstract entity id

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#14]
Let's say we have two csv files and two mappings: one for companies (`company_num`, `name`, `address`) and one for directors (`director_id`,`name`,`company_num`) - a standart situation for a mysql export from diffirent tables.  

When generating entities from them, we can't link director to company - simply because we can't get company entity_id from directors mapping (and vice versa).

The only way for now - is to create two entities: one 'full' from companies file (having all company fields - name, address, etc) and one 'stub' from directors file (containing only `company_num` since it's only one available there) - and then merge them outside Beast. 

My proposal is to create a resolver to generate and return `entity_id` without generating `entity`. 

E.g., for companies file we will have: 
```yaml
# just a simple Company entity
entities:
  company:
    schema: Company
    keys:
      - entity.registrationNumber
      # lets assume we will get a key '1234abcd' from this input
    properties:
      registrationNumber:
        column: company_num
      name:
        column: name
      address:
        column: address
```

And for directors we will have:
```yaml
entities:
  person:
    schema: Person
    keys:
      - entity.name
    properties:
      name:
        column: name
      # ... and other person's fields we have

  directorship:
    schema: Directorship
    keys:
      - entity.organization
      - entity.director
    properties:
      director: # we can link director by entity resolver
        entity: person
      organization: # but we can't link an organization - because we creating it's entity in other file/mapping
        our_custom_entity_id_resolver: # instead we will use our resolver
          - column.company_num # and give it list of columns to generate entity_id
                               # this will create entity_id for without creating an entity, 
                               # having same column/value as in company file will yield us same id '1234abcd'
                               # thus allowing us to link the entity from other file
```

I'm not sure whether this is a good idea, need you thoughts @dchaplinsky
