### ISSUE TITLE
entity_id generation is broken for properties with other entity

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#24]
Lets say we have an entity with other linked entity (e.g. `Company` with `addressEntity`).

When using `Company:addressEntity` as column for entity_id, Beast won't resolve an entity, using a constant id instead.

```
company:
  schema: Company
  keys: 
    - entity.addressEntity # this will output constant company ids, regardless of actual Address
  properties:
    addressEntity:
      entity: address_entity
```

As far I can see, [entity.get(key_path)](https://github.com/dchaplinsky/thebeast/blob/a25c4264f80d8f58356aeba227dd7eb6f0b3d808/thebeast/digest/abstract.py#L57) will resolve as entity schema name instead of actual entity id. 

E.g., code above will always use string `"Address"` to generate company entity id. 

I guess, it should resolve to actual `Address` entity id, and then use it to generate `Company` entity id?
