### ISSUE TITLE
Two-pass properties resolver for entities?

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#26]
Currently, `template` resolver works only if it's put after other resolves in mapping.

E.g. this will fail: 
```yaml
properties:
  name:
    template: "{{entity.firstName[0]}}" 
  firstName:
    literal: foobar 
```

Probably, this can be fixed if entity's properties will be resolved in two passes: firstly all `column`s and `literal`s, and then all `template`s and `variable`s. 

But the queston is: do we need to complicate such things?
