### ISSUE TITLE
Accessing entities between nested collections

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#30]
Let's say we have following data:

```json
{"name": "Іван Срака", "address": [ { "full": "вул. пушкіна, д. колотушкіна" }, { "full": "масква" } ] }
```

From it, we can generate two entities: one `Person` and two `Address`es. 

Problem is, we can not link this addresses to this person i.e., by making such config:

```yaml
  collections:
    root:
      path: "[@]" 
      collections:
        addresses: 
          path: "address"
          entities:
            address_entity:
              schema: Address
              keys:
                - entity.full
              properties:
                full:
                  column: full

      entities:
        person:
          schema: Person
          keys:
            - entity.name
          properties:
            addressEntity:
              entity: address_entity
            name:
              column: name
```

It will output three entities, but `Person` won't have `addressEntity` set.

It seems you can only reference parrent from child (as in [ukrainian_edr.yaml](https://github.com/dchaplinsky/thebeast/blob/main/thebeast/tests/sample/mappings/ukrainian_edr.yaml)), but not vice versa.

I've tried to do some magic with `template`, but:
- `record` only have current (nested) record;
- `variable` have variables nested to collection;
- jmespath [can't](https://github.com/jmespath/jmespath.js/issues/22) resolve parent node;

I see these options: 
1. fully implement nested entity relations (@dchaplinsky 👉👈🙄) to allow such links between entities;
2. implement something like `top_level_record` context variable to hold all data from top-most collection. E.g., for this example input it will hold whole input row as is. This with some magic will allow me to link person to it's addresses, and I'll be happy. But this is rather hacky option.
3. **or maybe you will say there's already implemented option for this and I just didn't found it myself**
