### ISSUE TITLE
Multiple `regex_replace` are ignored, only last one is applied

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#32]
Since `regex_replace` is a resolver, when defining it multiple times for same column, only last one will be applied. 

In case you have to clean rather dirty string, you can't conveniently do it via nice little steps, e.g.:

```yaml
            address:
              column: Address
              regex_replace: 
                regex: "^Адрес:\\s?"
                replace: ""
              regex_replace: 
                regex: ",\\sож\\.\\sвр\\.\\sдост\\.\\:\\s.+$"
                replace: ""
```

Surely, you can merge all regexes into ~~unreadable mess~~ single one or use pipeline of variables, but thats ugly.

To keep things simple, maybe `regex_replace` should be a transformer rather than resolver?
