### ISSUE TITLE
`anydate` transformer breaks when using `silent` and `dayfirst` at same time

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#39]
Looks like I've messed up somewhere, and now when using this config:

```yaml
transformer: 
  name: thebeast.contrib.transformers.anydate_parser
  params:
    dayfirst: true
    silent: true
```

Transformer will for some reason ignore `dayfirst`. 
I'll investigate and fix this.
