### ISSUE TITLE
Should not create entity if key is empty

### ISSUE THREAD

**Issue by Legless** [dchaplinsky/thebeast#4]
When defining entity like this: 

```
        address_entity:
          schema: Address
          keys:
            - record.address
          properties:
            country:
              literal: "ru"
            full:
              column: address
```

With empty column in ingested data, Beast will still output following statements (note empty `entity_id`):
```
id,entity_id,prop,prop_type,schema,value,meta:locale,meta:source,meta:transformation
44a60d21bd20bfebd2ba1190aff78ed7600a4d19,,id,id,Address,,,,
6ea5c3bb7a6a5ea9d511f66cfe83ee2a9fbee4b6,,country,country,Address,ru,ru,,
```

Expected result: do not create statements for entitites with empty key, even if it will have some properties set (like `country` in this example).

**Comment by Legless** [comment]
This also (i haven't tested yet, but in theory?) will allow some kind of filtering dataset, if keys will be based on template generated property, which will yield empty string, which is also will be a good feature.

I.e. 
```
          keys:
            - record.name
          properties:
            name:
              template: "{% if .... %}...{% endif %}"

```
