### ISSUE TITLE
`regex_replace` not working on `template` values?

### ISSUE THREAD

**Issue by yharahuts** [dchaplinsky/thebeast#49]
Given this config, field value still have spaces: 
```
template: "{{record.PASPSER}}"
regex_replace: 
  regex: "[^\\d]+"
  replace: ""
```

But with `column` instead of `template` - everything works as expected.

**Comment by dchaplinsky** [comment]
I cannot reproduce it, my friend:

```yaml
id: regex_test

meta: []

info:
  comments: No meta test file
  author: Dmytro Chaplynskyi
  created: "2023-01-02T20:19:00.1Z"
  modified: "2023-01-02T20:19:00.1Z"

ingest:
  cls: thebeast.ingest.CSVDictGlobReader
  params:
    input_uri: data/regex_test.csv

digest:
  meta:
    locale:
      literal: ru
  collections:
    root:
      path: "[@]"   # Wrap each record into the list

      entities:
        test_entity:
          schema: Person
          keys:
            - entity.name
          properties:
            name:
              template: "{{ record.name }}"
              regex_replace: 
                regex: "[^\\d]+"
                replace: ""
dump:
  cls: thebeast.dump.FTMLinesWriter
  params:
    # Just stdout it, so we can pipe it into the next tool
    output_uri: "/dev/stdout"
```

And the data:

```csv
name
12 23 34
12 3456
```


The output is:
```jsonlines
{"id": "267ab2a571ef98d6aa2f28cbfa589783cf0727c4", "properties": {"name": ["122334"]}, "schema": "Person"}
{"id": "85f977aa875c00e6b3189eef112c4b1144a4bc35", "properties": {"name": ["123456"]}, "schema": "Person"}
